### ISSUE TITLE
Help needed of set Heating temperature

### ISSUE THREAD

**Issue by Switchblade2** [william-sy/Daikin-BRP069A62#15]
Hi,

Taking a chance to ask for help as there is very limited documentation on Daikin integrations.  

I have a BRP069A62 connected to Daikin Altherma 3 and I'm using Node Red for my home Automation.
In Node Read I'm able to read data via WebSockets as well as turning on/off Power for heating and hot water tank.
The issue I have is in changing the target temperature. 

In one of your files (docs/files/notes/note2.txt line 78) I found this command:
{"m2m:rqp":{"op":1,"to":"/[0]/MNAE/1/Operation/TargetTemperature","fr":"/S","rqi":"","ty":4,"pc":{"m2m:cin":{"con":14,"cnf":"text/plain:0"}}}}

If I send this I only get the following response 
{"m2m:rsp":{"rsc":4102,"to":"/S","fr":"/[0]/MNAE/1/Operation/TargetTemperature"}

All valid responses has a "rsc" value that is 2000 or 2001 so I guess it is an error code.
Thanks to your work I've been able to check the UnitProfiles (0, 1 & 2) and the command Operation/TargetTemperature is there.

Any ideas on what I should change to make it work?
Thanks

**Comment by Meatballs1** [comment]
Are you using a value between -10 and 10? It's an offset to the target flow temp afaik

**Comment by Switchblade2** [comment]
From what I can see it is the Targeted Room temperature (that can be set via the Conecta app)

If I make the following call 
{"m2m:rqp": {"op": 2,"to": "/[0]/MNAE/1/Operation/TargetTemperature/la","fr": "/S","rqi": "rcxag"}}

then I get back the Targeted Room temperature in the response, 14 degrees C in this case.
{"m2m:rsp":{"rsc":2000,"rqi":"rcxag","to":"/S","fr":"/[0]/MNAE/1/Operation/TargetTemperature/la","pc":{"m2m:cin":{"rn":"0000001c","ri":"0012_0000001c","pi":"0012","ty":4,"ct":"20230209T094705Z","lt":"20230209T094705Z","st":28,"con":14}}}}

I'd like to find away to change this value through a WebSocket message.

At least in my set up I have a command called  "LeavingWaterTemperatureOffsetHeating" that I think is what you refer to.
It will only take -10 to +10 values.

**Comment by Meatballs1** [comment]
Ah yes probably right, I only have ext thermostats so no option to set a target internal temp

**Comment by Switchblade2** [comment]
Got it working, had a pair of unwanted "" in the ws call
