### ISSUE TITLE
The Old Daikin App for Android

### ISSUE THREAD

**Issue by parkyjimbo** [william-sy/Daikin-BRP069A62#16]
Dear william-sy
Do you still have the old App for android available, I have this wifi module installed on my Daikin display and would like to try and go cloudless. 
Any help is welcome, many thanks. 
Regards
Jim

**Comment by william-sy** [comment]
This should be it: 
[no-cloud.zip](https://github.com/user-attachments/files/16561197/no-cloud.zip)
Enjoy ;)
