### ISSUE TITLE
Another project

### ISSUE THREAD

**Issue by Frankkkkk** [william-sy/Daikin-BRP069A62#2]
Hi @william-sy ,

I've created python-daikin-altherma https://github.com/Frankkkkk/python-daikin-altherma which is a lib to talk to daikin altherma's on a more OO way.
Would you be willing to contribute to it ? Maybe we could join efforts and produce a nice lib ?

Cheers
Frank

**Comment by william-sy** [comment]
Very cool, Happy to help :)

**Comment by misko903** [comment]
Maybe MQTT Support? I would like to use it as a basic user in OpenHAB 💻 
thanks!

**Comment by william-sy** [comment]
Yes MQTT is on my todo list :)

**Comment by Spitfire69** [comment]
Hi there,

Can see that you are working with an MQTT version which is very interesting. I have made my own simple websocket version running with Appdeamon on Home Assistant.

Looking forward to see your progress :)

**Comment by william-sy** [comment]
@Spitfire69  First simple version is up :)

**Comment by Spitfire69** [comment]
Excellent, looks like you have added MQTT autodiscovery, I’m not 100% sure but I think HA has another autodiscovery than homie, what type is implemented? I’m using HA myself.
I do also note that heat handling is implemented but not boiler handling which I personally need to be able to throw away my old appdeamon script for good.

**Comment by william-sy** [comment]
Hi There, 

> what type is implemented?

I did not implement an auto discovery, just a generic MQTT with mosquito as a MQTT broker. If HA picks up all the pub/sub items automatically that is a bonus  👍 , I have not yet implemented this in my own HA (did not have the time) I just know the MOTT wokrs.

As I do not have a boiler myself hooked to the LAN adapter, you could open a new ticket with some raw data from your LAN module. So I can see if I can implement it in the MQTT / entire script. You can find the info you need to get this raw data here: `https://github.com/william-sy/Daikin-BRP069A62/blob/master/docs/documentation.md`  Also please not I cannot test this feature as again I dont have a boiler. So this would rely on you testing / validating.

Cheers!

ps. At some point i will add a HA MQTT config file.

**Comment by william-sy** [comment]
@Frankkkkk 

Hope you are doing well, I have been adding another bunch of  hours this pas weeks, and perhaps you have some quick recommendations to the branch `V1.2-work` ?

**Comment by Spitfire69** [comment]
Excellent! Will try to get it running in home assistant asap.

//Tommy

mån 19 apr. 2021 kl. 18:31 skrev William van Beek ***@***.***
