### ISSUE TITLE
Help needed using this in home assistant

### ISSUE THREAD

**Issue by HansWegman** [william-sy/Daikin-BRP069A62#7]
Hello Wiliam,

I have an altherma with a lan adapter and would like to get it integrated with my home assistant system. I am fairly new so need some clear pointers how to create temperature sensors and switches to control the altherma. I did manage to get it integrated within my Vera unit using node red and some examples code I picked up from somewhere but I guess with HASS it would be fairly straightforward to get the data in without using node-red.

Can you help out here?

**Comment by william-sy** [comment]
Hi Hans, 

Thank you for your message,
This spaghetti code has built in MQTT :) 
https://www.home-assistant.io/integrations/mqtt/

Once you have this code configured you can send the `-m` flag and it should start in MQTT mode. 
Home assistant should then be able to communicate. 

If there is any problems with this let me know. Its starting to become dark again for fall and winter so this project might get some more life into it :)
